filereadfull = open('file.txt', 'r')
print("\n Full file: \n")
print(filereadfull.read())
filereadfull.close()
fileread10 = open('file.txt','r')
print("\n First 10 characters: \n")
print(fileread10.read(10))
fileread10.close()
fileread1stline = open('file.txt','r')
print("\n First line: \n")
print(fileread1stline.readline())
fileread1stline.close()
fileread4lines = open('file.txt','r')
print("\n First 4 lines: \n")
print(fileread4lines.readline())
print(fileread4lines.readline())
print(fileread4lines.readline())
print(fileread4lines.readline())
fileread4lines.close()
fileloop = open('file.txt', 'r')
for x in fileloop:
    print(x)
fileloop.close()
